def print_hi(name):print(f'Hi,{name}')
print_hi('c++')
print_hi('java')
print_hi('python')
print_hi('c#')
print_hi('c')
print_hi('c++')
print_hi('java')
print_hi('python')
print_hi('c#')
print_hi('c')
print_hi('c++')
print_hi('java')
print_hi('python')
print_hi('c#')